check: "this is a check"
decrypt:
  decrypt_type:
    module: 'src.Decrypt.decryptions'
    class_name: 'Aes'
  key: MDEyMzQ1Njc4OWFiY2RlZg==
  aes:
    iv: YWJjZGVmMDEyMzQ1Njc4OQ==
translate:
  from_lang: 'ar'
  to_lang: 'en'